services:
  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./development/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
  php:
    build:
      context: development/php
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www/api
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
      - "8889:3306"
    environment:
      MYSQL_DATABASE: cryptoDB
      MYSQL_USER: crypto
      MYSQL_PASSWORD: crypto
      MYSQL_ROOT_PASSWORD: crypto
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: crypto
      PMA_PASSWORD: crypto
    volumes:
      - ./upload.ini:/usr/local/etc/php/php.ini
    ports:
      - "8888:80"
    ######### Volumes ###################################
volumes:
  database:
    driver: local
  redis:
    driver: local
